name = "workers"
compatibility_date = "2024-08-23"

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
# binding = "GitHubDatabase"
binding = "DB"
id = "6940f7b8725244efbaa5938794fe8e38"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

[ai]
binding = "AI"